---
- hosts: win
  remote_user: administrator
  vars:
    become_method: runas
    ansible_shell_type: powershell
    shell_type: powershell

  tasks:
    - name: Create local user
      win_user:
        name: jtespecial
        state: present # absent to remove a local user
        password: tHisS1%S4PWD!
